// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import auth "github.com/pPrecel/BeerKongServer/internal/auth"
import mock "github.com/stretchr/testify/mock"

// Auth is an autogenerated mock type for the Auth type
type Auth struct {
	mock.Mock
}

// GetAccount provides a mock function with given fields: _a0
func (_m *Auth) GetAccount(_a0 string) (auth.GoogleAccount, error) {
	ret := _m.Called(_a0)

	var r0 auth.GoogleAccount
	if rf, ok := ret.Get(0).(func(string) auth.GoogleAccount); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(auth.GoogleAccount)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
