// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import prisma "github.com/pPrecel/BeerKongServer/pkg/prisma/generated/prisma-client"
import resolver "github.com/pPrecel/BeerKongServer/internal/resolver"

// Composer is an autogenerated mock type for the Composer type
type Composer struct {
	mock.Mock
}

// Resolver provides a mock function with given fields: user
func (_m *Composer) Resolver(user *prisma.User) resolver.Resolver {
	ret := _m.Called(user)

	var r0 resolver.Resolver
	if rf, ok := ret.Get(0).(func(*prisma.User) resolver.Resolver); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(resolver.Resolver)
		}
	}

	return r0
}
