// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import http "net/http"
import mock "github.com/stretchr/testify/mock"

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// PrismaGQL provides a mock function with given fields: writer, request
func (_m *Handler) PrismaGQL(writer http.ResponseWriter, request *http.Request) {
	_m.Called(writer, request)
}
